pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "yourdockerhubusername/python-login"
    REMOTE_HOST = "ec2-user@<EC2_PUBLIC_IP>"
    REMOTE_KEY = credentials('ec2-ssh-key') // Jenkins credential
  }

  stages {
    stage('Clone Code') {
      steps {
        git 'https://github.com/<yourusername>/python-login-app.git'
      }
    }

    stage('Build Docker Image') {
      steps {
        script {
          sh 'docker build -t $DOCKER_IMAGE .'
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh """
            echo $PASS | docker login -u $USER --password-stdin
            docker push $DOCKER_IMAGE
          """
        }
      }
    }

    stage('Deploy to EC2') {
      steps {
        sshagent (credentials: ['ec2-ssh-key']) {
          sh """
            ssh -o StrictHostKeyChecking=no $REMOTE_HOST '
              docker pull $DOCKER_IMAGE &&
              docker stop loginapp || true &&
              docker rm loginapp || true &&
              docker run -d --name loginapp -p 80:5000 $DOCKER_IMAGE
            '
          """
        }
      }
    }
  }
}
